### PR TITLE
Optimize the import format

### PR DESCRIPTION
**Pull request by Yuxiaoy1**
Optimize the import format using Python's standard grouping mechanism (parentheses), refering to [PEP 328](https://legacy.python.org/dev/peps/pep-0328/#rationale-for-absolute-imports).

### CODE REVIEW

**Comment by greyli** [comment]
Thank you for working on this, but it's intentional to import each APIs in a separate line. I think it will make it easier to track the change of import statements. I prefer to make the imports more consistent in this style in the whole project (update the import from typing and all the imports in tests).

**Comment by Yuxiaoy1** [comment]
I see what you meant here, but I think it's also very easy to track the changes of import statement using the parentheses, unless you're making really big changes, I assume it's a low probability. besides, this would be more pythonic.

**Comment by greyli** [comment]
I still prefer the origin import style, it's more readable and in consist with Flask's import style.

**Comment by greyli** [comment]
Closed in favor of #15.

**Pull request closed without merging**
